### ISSUE TITLE
uncss works incorrectly

### ISSUE THREAD

**Issue by vadimfilimonov** [ruport-digital/rutorika-template#12]
Когда uncss проходится по html файлам - он пытается открыть [scripts](https://github.com/ruport-digital/rutorika-template/blob/main/dev/res/templates/components/_scripts.html)

У него этого сделать не получается и билд либо тихо [останавливается](https://github.com/ruport-digital/rutorika-template/runs/1845969609?check_suite_focus=true), либо просто печатает предупреждение

![image](https://user-images.githubusercontent.com/11225648/107126822-33afc200-68c3-11eb-82f3-7296834de4f7.png)

Я вижу два быстрых способа пофиксить это:
- Заменить путь к скриптам с `/res/js/scripts.min.js` на `./res/js/scripts.min.js`
- Удалить `grunt-uncss`

Предлагаю последний, т.к. мы никогда не используем этот плагин

**Comment by enter000** [comment]
ну я нашел жалобы на такую же ошибку - можно поставить [purgecss](https://www.npmjs.com/package/purgecss) - так-то полезный функционал, лишним не будет
